export type BlogBlockType = 'paragraph'|'h2'|'h3'|'image'|'list'|'quote'|'faq'|'cta'|'divider';
export type BlogBlock = { blockId:string; type:BlogBlockType; title?:string; text?:string; assetId?:string };
export type BlogMedicalReview = {
  required: boolean|null;
  status: 'not-reviewed'|'check-needed'|'preparing'|'submitted'|'revision-requested'|'approved'|'not-required';
  reviewNumber: string;
  reviewedAt: string;
  locked: boolean;
};
export type BlogProject = {
  projectId:string;
  advertiserId:string;
  advertiserName:string;
  industry:string;
  platform:string;
  contentType:string;
  purpose:string;
  primaryKeyword:string;
  secondaryKeywords:string[];
  region:string;
  targetLength:number;
  tone:string;
  referenceText:string;
  options:{style:boolean;advertiserInfo:boolean;photos:boolean;compliance:boolean;seo:boolean;medical:boolean};
  titleOptions:string[];
  selectedTitle:string;
  blocks:BlogBlock[];
  status:'draft'|'writing'|'review'|'revision'|'approved'|'publish-ready'|'published'|'archived';
  complianceStatus:string;
  medicalReview:BlogMedicalReview;
  seoScore:number;
  complianceIssues:ComplianceIssue[];
  assetIds:string[];
  publishStatus:string;
  scheduledAt?:string;
  publishedUrl?:string;
  createdAt:string;
  updatedAt:string;
};
export type BlogStyleProfile = {
  advertiserId:string;
  tone:string;
  rules:string[];
  preferredPhrases:string[];
  prohibitedPhrases:string[];
  cta:string;
  sourceTexts:string[];
  updatedAt?:string;
};
export type BlogAsset = {assetId:string;advertiserId:string;name:string;url:string;tags:string[];createdAt:string};
export type ComplianceIssue = {
  id:string;
  severity:'danger'|'warning'|'info';
  category:string;
  phrase:string;
  reason:string;
  suggestion:string;
  blockId?:string;
};
