import { useEffect, useMemo, useState } from 'react';
import { Search } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { MetricsDateBar } from '../components/MetricsDateBar';
import { useAdvertiserFilter } from '../context/AdvertiserFilterContext';
import { useMetricsQuery } from '../context/MetricsQueryContext';
import { apiFetch } from '../hooks/useApi';
import { metricQuery } from '../hooks/useMetrics';
import type { CreativeDailyMetricRow, CreativeMetricRow, MetricsMeta } from '../types/metrics';
import { matchesAdvertiserFilter } from '../utils/advertiserMatch';

type Response={rows:CreativeMetricRow[];dailyRows:CreativeDailyMetricRow[];meta:MetricsMeta};
type FatigueRow=CreativeMetricRow&{score:number;cpm3Change:number|null;cpm7Change:number|null;ctr7Change:number|null;cpc7Change:number|null;activeDays:number};
const pct=(a:number,b:number)=>b>0?(a-b)/b*100:null;
function aggregate(rows:CreativeDailyMetricRow[]){const x=rows.reduce((a,r)=>({impressions:a.impressions+r.impressions,clicks:a.clicks+r.clicks,spend:a.spend+r.spend}),{impressions:0,clicks:0,spend:0});return{...x,cpm:x.impressions?x.spend/x.impressions*1000:0,ctr:x.impressions?x.clicks/x.impressions*100:0,cpc:x.clicks?x.spend/x.clicks:0}}
function lastDates(rows:CreativeDailyMetricRow[],n:number,offset=0){const dates=[...new Set(rows.map(r=>r.date))].sort().reverse().slice(offset,offset+n);const s=new Set(dates);return rows.filter(r=>s.has(r.date))}
function fatigue(base:CreativeMetricRow, daily:CreativeDailyMetricRow[]):FatigueRow{const recent3=aggregate(lastDates(daily,3)),prev3=aggregate(lastDates(daily,3,3)),recent7=aggregate(lastDates(daily,7)),prev7=aggregate(lastDates(daily,7,7));const cpm3=pct(recent3.cpm,prev3.cpm),cpm7=pct(recent7.cpm,prev7.cpm),ctr=pct(recent7.ctr,prev7.ctr),cpc=pct(recent7.cpc,prev7.cpc);let score=0;if((cpm3||0)>=50)score+=25;else if((cpm3||0)>=25)score+=12;if((cpm7||0)>=30)score+=25;else if((cpm7||0)>=15)score+=12;if((ctr||0)<=-20)score+=25;else if((ctr||0)<=-10)score+=12;if((cpc||0)>=30)score+=20;else if((cpc||0)>=15)score+=10;const activeDays=new Set(daily.filter(r=>r.impressions>0||r.spend>0).map(r=>r.date)).size;if(activeDays>=21)score+=5;return{...base,score:Math.min(100,score),cpm3Change:cpm3,cpm7Change:cpm7,ctr7Change:ctr,cpc7Change:cpc,activeDays}}
const fmt=(n:number|null,reverse=false)=>n==null?'-':`${n>0?'+':''}${n.toFixed(1)}%${reverse&&n<0?' ↓':''}`;

export function CreativeFatiguePage(){
  const {range}=useMetricsQuery();const {filterValue}=useAdvertiserFilter();const [data,setData]=useState<Response|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [q,setQ]=useState('');
  useEffect(()=>{let alive=true;setLoading(true);setError('');apiFetch<Response>(`/metrics/creatives?${metricQuery(range)}`).then(r=>alive&&setData(r)).catch(e=>{if(alive){setData(null);setError(e instanceof Error?e.message:String(e))}}).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[range.from,range.to]);
  const rows=useMemo(()=>{if(!data)return[];return data.rows.map(base=>fatigue(base,data.dailyRows.filter(d=>d.advertiserId===base.advertiserId&&d.channel===base.channel&&d.adId===base.adId))).filter(r=>matchesAdvertiserFilter(r.advertiserName||r.advertiserId,filterValue)&&`${r.adName} ${r.campaignName||''}`.toLowerCase().includes(q.trim().toLowerCase())).sort((a,b)=>b.score-a.score)},[data,filterValue,q]);
  const connected=data?.meta.connections.filter(c=>c.status==='connected')||[];
  return <div><PageHeader title="소재 피로도 관리" description="동일 creative_daily_metrics에서 최근 3일·7일 구간의 CPM·CTR·CPC 변화를 계산합니다." action={<div className="ops-search compact"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="소재·캠페인 검색"/></div>}/><MetricsDateBar/>{error&&<div className="status-banner danger">{error}</div>}<div className="status-banner neutral" style={{marginBottom:12}}>{connected.length?'실제 소재 일별 성과 기준입니다.':'연동된 소재 성과 매체가 없습니다.'} 빈도·도달 데이터는 현재 저장하지 않아 피로도 점수에 포함하지 않습니다.</div><div className="fatigue-stat-grid"><div><span>🔴 위험 (85+)</span><strong>{rows.filter(r=>r.score>=85).length}건</strong></div><div><span>🟡 주의 (70+)</span><strong>{rows.filter(r=>r.score>=70&&r.score<85).length}건</strong></div><div><span>🟢 정상</span><strong>{rows.filter(r=>r.score<70).length}건</strong></div></div><section className="card ops-card"><div className="table-scroll"><table className="ops-table fatigue-table"><thead><tr><th>소재</th><th>매체</th><th>피로도</th><th>3일 CPM 변화</th><th>7일 CPM 변화</th><th>7일 CTR 변화</th><th>7일 CPC 변화</th><th>활성일</th><th>기간 광고비</th></tr></thead><tbody>{loading?<tr><td colSpan={9} className="empty-cell">불러오는 중...</td></tr>:rows.length===0?<tr><td colSpan={9} className="empty-cell">분석할 실제 소재 일별 데이터가 없습니다.</td></tr>:rows.map(r=><tr key={`${r.advertiserId}-${r.channel}-${r.adId}`}><td><div className="creative-name-cell">{r.thumbnailUrl?<img className="creative-thumb" src={r.thumbnailUrl} alt=""/>:<span className="creative-thumb"/>}<span><b>{r.adName}</b><small>{r.campaignName||'-'}</small></span></div></td><td>{r.channel==='meta'?'Meta':r.channel==='naver'?'네이버':r.channel}</td><td><b>{r.score}</b>점</td><td>{fmt(r.cpm3Change)}</td><td>{fmt(r.cpm7Change)}</td><td>{fmt(r.ctr7Change,true)}</td><td>{fmt(r.cpc7Change)}</td><td>{r.activeDays}일</td><td>₩{Math.round(r.spend).toLocaleString()}</td></tr>)}</tbody></table></div><div className="footnote">점수는 선택 기간 안에서 소재별 일별 데이터가 충분한 경우에만 변화율을 계산합니다. 데이터가 없는 지표를 0으로 가장하지 않습니다.</div></section></div>;
}
