import { useMemo, useState, type CSSProperties, type ReactNode } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import {
  AlertTriangle, ArrowDownRight, ArrowLeft, ArrowUpRight, BarChart3, ChevronRight,
  CircleDollarSign, Clapperboard, CopyPlus, Database, FileText, Gauge, Image as ImageIcon,
  MousePointerClick, RefreshCw, Search, Sparkles, Target, TrendingDown, TrendingUp,
  UsersRound, Wand2, WalletCards
} from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { loadDbRows } from '../utils/dbDataStore';
import { loadCreativeAnalysisRows, creativeInsight, normalizeCreativeMedia, type CreativeAnalysisRow } from '../analytics/creativeAnalysis';
import { calculateCreativeFatigue } from '../analytics/creativeFatigueAnalysis';
import { analyzeCreativePatterns, type CreativePattern } from '../analytics/creativePatternAnalysis';
import { saveCreativeBrief } from '../utils/creativeBriefStore';

const MEDIA_COLORS:Record<string,string>={'메타':'#4776ff','네이버':'#03c75a','구글 검색':'#6b7280','유튜브':'#ef4444','당근':'#ff6f0f','카카오':'#f5c400','틱톡':'#111827'};
const periods=['최근 7일','최근 14일','최근 30일','이번 달','전체'];
const confidenceTone:Record<string,string>={'높음':'good','보통':'neutral','참고':'warning','판단 보류':'muted'};
const money=(n:number)=>n?`₩${Math.round(n).toLocaleString()}`:'-';
const pct=(n:number,digits=1)=>Number.isFinite(n)?`${n.toFixed(digits)}%`:'-';
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function addDays(value:string,days:number){const d=new Date(value+'T00:00:00');d.setDate(d.getDate()+days);return iso(d);}
function periodRange(period:string,latest:string){
  if(!latest||period==='전체') return {from:'',to:''};
  if(period==='이번 달') return {from:latest.slice(0,7)+'-01',to:latest};
  const days=Number(period.match(/\d+/)?.[0]||30); return {from:addDays(latest,-days+1),to:latest};
}
function statusTone(row:CreativeAnalysisRow){return row.analysisStatus==='매우 우수'||row.analysisStatus==='우수'?'good':row.analysisStatus==='정상'?'neutral':row.analysisStatus==='주의'?'warning':row.analysisStatus==='개선 필요'?'bad':'muted';}
function fatigueTone(row:CreativeAnalysisRow){const score=row.fatigueScore;return score===undefined?'muted':score>=80?'bad':score>=60?'warning':score>=35?'neutral':'good';}
function previewStyle(row:CreativeAnalysisRow){
  const value=row.creative.thumb;
  if(/^https?:|^data:|^\//.test(value)) return {backgroundImage:`url(${value})`,backgroundSize:'cover',backgroundPosition:'center'} as CSSProperties;
  const hue=(row.creative.id.split('').reduce((a,c)=>a+c.charCodeAt(0),0)*17)%360;
  return {background:`linear-gradient(145deg,hsl(${hue} 52% 28%),hsl(${(hue+48)%360} 68% 72%))`} as CSSProperties;
}
function CreativePreview({row,large=false}:{row:CreativeAnalysisRow;large?:boolean}){return <div className={`creative-analysis-preview ${large?'large':''}`} style={previewStyle(row)}>{!/^https?:|^data:|^\//.test(row.creative.thumb)&&<span>{row.creative.thumb}</span>}<em>{row.creative.type}</em></div>}
function MiniKpi({label,value,sub,icon}:{label:string;value:string;sub?:string;icon:ReactNode}){return <article className="creative-analysis-kpi"><div>{icon}<span>{label}</span></div><strong>{value}</strong>{sub&&<small>{sub}</small>}</article>}
function Sparkline({values}:{values:number[]}){
  if(!values.length)return <div className="creative-spark-empty">데이터 없음</div>;
  const max=Math.max(...values,1),min=Math.min(...values,0),span=Math.max(1,max-min),points=values.map((v,i)=>`${i/(Math.max(1,values.length-1))*100},${90-(v-min)/span*75}`).join(' ');
  return <svg className="creative-spark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points}/></svg>;
}
function PatternTable({title,rows}:{title:string;rows:CreativePattern[]}){return <section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>{title}</h3><p>표본 수와 실제 연결 지표를 함께 봅니다.</p></div></div>{rows.length?<div className="creative-pattern-list">{rows.slice(0,8).map(row=><div key={row.key}><div><b>{row.label}</b><small>{row.kind} · {row.count}개 소재</small></div><span>CTR <b>{row.avgCtr?pct(row.avgCtr,2):'-'}</b></span><span>CPA <b>{row.avgCpa?money(row.avgCpa):'-'}</b></span><span>유효DB율 <b>{row.avgValidDbRate?pct(row.avgValidDbRate):'-'}</b></span><em className={confidenceTone[row.confidence]}>{row.confidence}</em></div>)}</div>:<p className="creative-analysis-empty">비교 가능한 패턴 표본이 아직 부족합니다.</p>}</section>}

export function CreativeAnalysisPage(){
  const navigate=useNavigate(); const [params,setParams]=useSearchParams();
  const [period,setPeriod]=useState(params.get('period')||'최근 30일');
  const [query,setQuery]=useState(''); const [sort,setSort]=useState<'score'|'spend'|'ctr'|'cpa'|'db'|'fatigue'>('score'); const [dir,setDir]=useState<'desc'|'asc'>('desc');
  const rawDb=loadDbRows(); const latestDb=(()=>{const dates=rawDb.map(row=>row.date).sort();return dates[dates.length-1]||''})(); const range=periodRange(period,latestDb);
  const scopedDb=rawDb.filter(row=>(!range.from||row.date>=range.from)&&(!range.to||row.date<=range.to));
  const allRows=useMemo(()=>loadCreativeAnalysisRows(scopedDb),[JSON.stringify(scopedDb)]);
  const advertiser=params.get('advertiser')||''; const media=params.get('media')||''; const campaign=params.get('campaign')||''; const type=params.get('type')||''; const selectedId=params.get('creative')||'';
  const advertisers=[...new Set(allRows.map(r=>r.creative.brand))].sort((a,b)=>a.localeCompare(b,'ko'));
  const medias=[...new Set(allRows.filter(r=>!advertiser||r.creative.brand===advertiser).map(r=>normalizeCreativeMedia(r.creative.platform)))].sort((a,b)=>a.localeCompare(b,'ko'));
  const campaigns=[...new Set(allRows.filter(r=>(!advertiser||r.creative.brand===advertiser)&&(!media||r.creative.platform===media)).map(r=>r.campaignName).filter(v=>v&&v!=='-'))].sort((a,b)=>a.localeCompare(b,'ko'));
  const types=[...new Set(allRows.map(r=>r.creative.type))];
  const rows=allRows.filter(row=>(!advertiser||row.creative.brand===advertiser)&&(!media||normalizeCreativeMedia(row.creative.platform)===media)&&(!campaign||row.campaignName===campaign)&&(!type||row.creative.type===type));
  const selected=selectedId?allRows.find(row=>row.creative.id===selectedId):undefined;
  const patterns=analyzeCreativePatterns(rows);
  const usable=rows.filter(r=>r.hasPerformance||r.hasDb);
  const totalSpend=usable.reduce((a,r)=>a+r.spend,0),totalImpressions=usable.reduce((a,r)=>a+r.impressions,0),totalClicks=usable.reduce((a,r)=>a+r.clicks,0),totalDb=usable.reduce((a,r)=>a+r.db,0),totalValid=usable.reduce((a,r)=>a+r.validDb,0);
  const avgCpa=totalDb?totalSpend/totalDb:0,avgCtr=totalImpressions?totalClicks/totalImpressions*100:0;
  const scored=[...rows].filter(r=>r.score!==undefined).sort((a,b)=>(b.score||0)-(a.score||0)); const best=scored.slice(0,3),worst=[...scored].reverse().slice(0,3);
  const table=[...rows].filter(r=>(r.creative.name+r.creative.brand+r.creative.platform+r.campaignName+r.hookTypes.join(' ')+r.cta).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{
    const v=(r:CreativeAnalysisRow)=>sort==='score'?(r.score??-1):sort==='spend'?r.spend:sort==='ctr'?r.ctr:sort==='cpa'?(r.cpa||Number.MAX_SAFE_INTEGER):sort==='db'?r.db:(r.fatigueScore??-1);
    const diff=v(a)-v(b); return dir==='desc'?-diff:diff;
  });
  const expanded=scored.filter(r=>(r.kpiAchievement??r.score??0)>=110 || ((r.score??0)>=82&&(r.fatigueScore??0)<55)).slice(0,4);
  const replace=scored.filter(r=>(r.score??100)<55 || (r.fatigueScore??0)>=70).sort((a,b)=>(a.score??100)-(b.score??100)).slice(0,4);
  const rising=scored.filter(r=>r.performance?.trend?.length&&r.performance.trend[r.performance.trend.length-1]>r.performance.trend[0]*1.15).slice(0,4);
  const falling=scored.filter(r=>r.performance?.trend?.length&&r.performance.trend[r.performance.trend.length-1]<r.performance.trend[0]*0.75).slice(0,4);
  const updateParam=(key:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);if(key==='advertiser'){next.delete('media');next.delete('campaign');next.delete('creative')}if(key==='media'){next.delete('campaign');next.delete('creative')}if(key==='campaign')next.delete('creative');setParams(next,{replace:true});};
  const createBrief=(row:CreativeAnalysisRow)=>{
    const fatigue=calculateCreativeFatigue(row); const weak:string[]=[];
    if(fatigue.level==='높음'||fatigue.level==='매우 높음')weak.push('소재 피로 신호 완화');
    if(row.hasDb&&row.peerValidRate&&row.validDbRate<row.peerValidRate)weak.push('유효 DB 품질 개선');
    if(row.peerCtr&&row.ctr<row.peerCtr)weak.push('첫 화면/후킹 클릭 반응 개선');
    saveCreativeBrief({sourceCreativeId:row.creative.id,advertiserName:row.creative.brand,campaignId:row.creative.campaignId,campaignName:row.campaignName,creativeType:row.creative.type,winningElements:[...row.hookTypes.filter(x=>x!=='미분류'),...(row.cta!=='미분류'?[`CTA: ${row.cta}`]:[]),...row.creative.tags.slice(0,3)],weakElements:weak,recommendedHook:row.hookTypes.find(x=>x!=='미분류'),recommendedCta:row.cta!=='미분류'?row.cta:undefined,recommendedLength:row.creative.type==='영상'?'기존 우수 패턴 길이 유지 후 짧은 변형 테스트':undefined,objectiveMetric:row.kpiLabel,createdAt:new Date().toISOString()});
    navigate(`/content/ad-creation?sourceCreative=${encodeURIComponent(row.creative.id)}`);
  };

  if(selected){
    const fatigue=calculateCreativeFatigue(selected); const dbMatch=selected.hasDb; const peerCpaDiff=selected.peerCpa&&selected.cpa?((selected.peerCpa-selected.cpa)/selected.peerCpa*100):undefined;
    return <div className="creative-analysis-page"><button className="creative-back" onClick={()=>updateParam('creative','')}><ArrowLeft size={16}/> 전체 소재 분석</button><PageHeader title={`소재 분석 · ${selected.creative.name}`} description={`${selected.creative.brand} · ${normalizeCreativeMedia(selected.creative.platform)} · ${selected.campaignName}`}/>
      <section className="card creative-detail-hero"><CreativePreview row={selected} large/><div className="creative-detail-meta"><span className="creative-media-badge" style={{borderColor:MEDIA_COLORS[normalizeCreativeMedia(selected.creative.platform)]||'#64748b',color:MEDIA_COLORS[normalizeCreativeMedia(selected.creative.platform)]||'#475569'}}>{normalizeCreativeMedia(selected.creative.platform)}</span><h2>{selected.creative.name}</h2><p>{selected.creative.copy}</p><div className="creative-tag-row">{selected.hookTypes.map(t=><span key={t}>{t}</span>)}<span>{selected.cta}</span>{selected.creative.tags.slice(0,4).map(t=><span key={t}>{t}</span>)}</div><div className="creative-detail-actions"><Link className="btn secondary" to={`/creatives/library/${selected.creative.id}`}>소재 관리에서 확인</Link><Link className="btn secondary" to={`/assets/creatives?asset=${encodeURIComponent(selected.creative.assetId||`creative-${selected.creative.id}`)}`}>원본 자산 보기</Link><button className="btn primary" onClick={()=>createBrief(selected)}><Wand2 size={15}/> 이 소재 기반 새 광고 만들기</button></div></div></section>
      <section className="creative-analysis-kpi-grid"><MiniKpi icon={<WalletCards/>} label="광고비" value={money(selected.spend)} sub={selected.hasPerformance?'소재 성과 연결':'성과 데이터 미연결'}/><MiniKpi icon={<MousePointerClick/>} label="CTR" value={selected.impressions?pct(selected.ctr,2):'-'} sub={selected.peerCtr?`동일 조건 평균 ${pct(selected.peerCtr,2)}`:'비교 표본 없음'}/><MiniKpi icon={<Database/>} label="실제 DB" value={dbMatch?selected.db.toLocaleString():'-'} sub={dbMatch?`유효 DB ${selected.validDb.toLocaleString()}`:'creativeId/소재명 연결 필요'}/><MiniKpi icon={<UsersRound/>} label="유효 DB율" value={dbMatch?pct(selected.validDbRate):'-'} sub={selected.peerValidRate?`동일 조건 평균 ${pct(selected.peerValidRate)}`:'-'}/><MiniKpi icon={<CircleDollarSign/>} label="DB 비용" value={selected.cpa?money(selected.cpa):'-'} sub={peerCpaDiff===undefined?'-':`동일 조건 대비 ${peerCpaDiff>=0?'우수 ':'높음 '}${Math.abs(peerCpaDiff).toFixed(1)}%`}/><MiniKpi icon={<Target/>} label="성과점수" value={selected.score===undefined?'-':`${selected.score}점`} sub={selected.analysisStatus}/><MiniKpi icon={<Gauge/>} label="피로도" value={fatigue.score===undefined?'-':`${fatigue.score}점`} sub={`${fatigue.level} · ${fatigue.lifecycle}`}/><MiniKpi icon={<Sparkles/>} label="대표 KPI" value={selected.kpiAchievement===undefined?'미설정':`${selected.kpiAchievement.toFixed(0)}%`} sub={selected.kpiLabel}/></section>
      <div className="creative-analysis-two"><section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>성과 추이</h3><p>기존 소재 보고서에 연결된 구간 추이입니다.</p></div></div>{selected.performance?.trend?.length?<><Sparkline values={selected.performance.trend}/><div className="creative-trend-labels"><span>초기 {selected.performance.trend[0]}</span><span>최근 {selected.performance.trend[selected.performance.trend.length-1]}</span></div></>:<p className="creative-analysis-empty">기간별 소재 성과 데이터가 없습니다.</p>}</section><section className="card creative-analysis-panel"><h3>전환 퍼널</h3>{selected.hasPerformance||selected.hasDb?<div className="creative-funnel"><div><span>노출</span><b>{selected.impressions?selected.impressions.toLocaleString():'-'}</b></div><i>↓ {selected.impressions?pct(selected.ctr,2):'-'}</i><div><span>클릭</span><b>{selected.clicks?selected.clicks.toLocaleString():'-'}</b></div><i>↓ {selected.clicks&&selected.db?pct(selected.cvr,2):'-'}</i><div><span>실제 DB</span><b>{selected.hasDb?selected.db.toLocaleString():'-'}</b></div><i>↓ {selected.db?pct(selected.validDbRate):'-'}</i><div><span>유효 DB</span><b>{selected.hasDb?selected.validDb.toLocaleString():'-'}</b></div><i>↓ {selected.validDb?pct(selected.contractRate):'-'}</i><div><span>계약</span><b>{selected.hasDb?selected.contracts.toLocaleString():'-'}</b></div></div>:<p className="creative-analysis-empty">전환 퍼널을 계산할 데이터가 없습니다.</p>}</section></div>
      <div className="creative-analysis-two"><section className="card creative-analysis-panel"><h3>성과 변화 원인</h3><div className="creative-driver-card"><b>{creativeInsight(selected)}</b><p>소재 분석은 연결된 CTR·CPC·실제 DB·유효 DB·피로도 지표의 관계를 규칙 기반으로 해석합니다. 직접적인 인과관계로 단정하지 않습니다.</p><ul>{selected.peerCtr&&<li>CTR: 현재 {pct(selected.ctr,2)} / 동일 조건 평균 {pct(selected.peerCtr,2)}</li>}{selected.peerValidRate&&<li>유효 DB율: 현재 {pct(selected.validDbRate)} / 평균 {pct(selected.peerValidRate)}</li>}{selected.peerCpa&&<li>DB 비용: 현재 {money(selected.cpa)} / 평균 {money(selected.peerCpa)}</li>}</ul></div></section><section className="card creative-analysis-panel"><h3>피로도 근거</h3><div className={`creative-fatigue-score ${fatigueTone(selected)}`}><strong>{fatigue.score===undefined?'-':fatigue.score}</strong><span>{fatigue.level}</span></div><ul className="creative-reason-list">{fatigue.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></section></div>
      <div className="creative-analysis-two"><section className="card creative-analysis-panel"><h3>후킹 · CTA · 소재 태그</h3><div className="creative-attribute-grid"><div><span>후킹</span><b>{selected.hookTypes.join(' · ')}</b></div><div><span>CTA</span><b>{selected.cta}</b></div><div><span>소재 유형</span><b>{selected.creative.type}</b></div><div><span>광고 목표</span><b>{selected.creative.objective}</b></div></div><p className="creative-correlation-note">태그별 성과는 같은 광고주·매체·목적의 유사 소재를 우선 비교합니다. 관찰된 차이를 인과관계로 표현하지 않습니다.</p></section><section className="card creative-analysis-panel"><h3>동일 조건 평균 비교</h3><div className="creative-peer-grid"><div><span>비교 표본</span><b>{selected.peerCount}개</b></div><div><span>CTR</span><b>{selected.peerCtr?pct(selected.peerCtr,2):'-'}</b></div><div><span>DB 비용</span><b>{selected.peerCpa?money(selected.peerCpa):'-'}</b></div><div><span>유효 DB율</span><b>{selected.peerValidRate?pct(selected.peerValidRate):'-'}</b></div></div></section></div>
      <section className="card creative-analysis-panel creative-brief-panel"><div><Sparkles size={22}/><h3>다음 소재 제작 제안</h3><p>{selected.score!==undefined&&selected.score>=80?'현재 우수한 요소를 유지하면서 후킹·CTA·길이 중 한 요소씩 변형해 테스트하세요.':'성과가 낮은 요소를 그대로 복제하기보다 후킹 또는 전환 단계 가설을 하나씩 분리해 새 버전을 테스트하세요.'}</p><div className="creative-tag-row">{selected.hookTypes.filter(x=>x!=='미분류').map(t=><span key={t}>{t}</span>)}{selected.cta!=='미분류'&&<span>CTA {selected.cta}</span>}<span>{selected.creative.type}</span></div></div><button className="btn primary" onClick={()=>createBrief(selected)}><Wand2 size={16}/> 이 분석으로 광고 제작</button><Link className="btn secondary" to={`/content/templates?sourceCreative=${encodeURIComponent(selected.creative.id)}`}><FileText size={16}/> 템플릿으로 저장</Link></section>
      {selected.dataNotes.length>0&&<div className="creative-data-note"><AlertTriangle size={16}/><span>{selected.dataNotes.join(' · ')}</span></div>}
    </div>;
  }

  return <div className="creative-analysis-page"><PageHeader title="소재 분석" description="이미지·영상·카피의 광고 성과, 실제 DB 품질, 피로도와 성공 패턴을 분석하고 콘텐츠 제작으로 연결합니다."/>
    <section className="card creative-analysis-filters"><label>기간<select value={period} onChange={e=>{setPeriod(e.target.value);const next=new URLSearchParams(params);next.set('period',e.target.value);setParams(next,{replace:true})}}>{periods.map(v=><option key={v}>{v}</option>)}</select></label><label>광고주<select value={advertiser} onChange={e=>updateParam('advertiser',e.target.value)}><option value="">전체</option>{advertisers.map(v=><option key={v}>{v}</option>)}</select></label><label>매체<select value={media} onChange={e=>updateParam('media',e.target.value)}><option value="">전체</option>{medias.map(v=><option key={v}>{v}</option>)}</select></label><label>캠페인<select value={campaign} onChange={e=>updateParam('campaign',e.target.value)}><option value="">전체</option>{campaigns.map(v=><option key={v}>{v}</option>)}</select></label><label>소재 유형<select value={type} onChange={e=>updateParam('type',e.target.value)}><option value="">전체</option>{types.map(v=><option key={v}>{v}</option>)}</select></label><button className="btn secondary" onClick={()=>{setPeriod('최근 30일');setParams({}, {replace:true});setQuery('')}}><RefreshCw size={14}/> 초기화</button></section>
    <section className="creative-analysis-kpi-grid"><MiniKpi icon={<ImageIcon/>} label="분석 소재" value={`${rows.length}개`} sub={`성과 연결 ${usable.length}개`}/><MiniKpi icon={<WalletCards/>} label="광고비" value={money(totalSpend)} sub="연결 소재 합계"/><MiniKpi icon={<MousePointerClick/>} label="클릭" value={totalClicks?totalClicks.toLocaleString():'-'} sub={totalImpressions?`평균 CTR ${pct(avgCtr,2)}`:'광고 성과 미연결'}/><MiniKpi icon={<Database/>} label="실제 DB" value={totalDb?totalDb.toLocaleString():'-'} sub={totalValid?`유효 DB ${totalValid.toLocaleString()}`:'Google Sheets 소재ID 연결 시 집계'}/><MiniKpi icon={<CircleDollarSign/>} label="평균 DB 비용" value={avgCpa?money(avgCpa):'-'} sub="실제 DB 연결 기준"/><MiniKpi icon={<Target/>} label="성과 우수" value={`${scored.filter(r=>(r.score??0)>=80).length}개`} sub="성과점수 80+"/><MiniKpi icon={<Gauge/>} label="피로 주의" value={`${rows.filter(r=>(r.fatigueScore??0)>=60).length}개`} sub="피로도 60+"/><MiniKpi icon={<Sparkles/>} label="패턴 표본" value={`${patterns.patterns.length}개`} sub={`우수 패턴 ${patterns.winning.length}개`}/></section>

    <div className="creative-analysis-two creative-featured-grid"><section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>성과 우수 소재</h3><p>성과점수와 KPI/DB 품질을 종합해 봅니다.</p></div></div><div className="creative-featured-cards">{best.length?best.map(row=><button key={row.creative.id} onClick={()=>updateParam('creative',row.creative.id)}><CreativePreview row={row}/><div><b>{row.creative.name}</b><small>{row.creative.brand} · {normalizeCreativeMedia(row.creative.platform)}</small><span><em className="good">{row.score}점</em>{row.db>0&&<>DB {row.db.toLocaleString()}</>}{row.cpa>0&&<>CPA {money(row.cpa)}</>}</span></div><ChevronRight size={16}/></button>):<p className="creative-analysis-empty">평가 가능한 소재 성과가 없습니다.</p>}</div></section><section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>개선 필요 소재</h3><p>저성과 또는 피로 신호가 큰 소재를 우선 표시합니다.</p></div></div><div className="creative-featured-cards">{worst.length?worst.map(row=><button key={row.creative.id} onClick={()=>updateParam('creative',row.creative.id)}><CreativePreview row={row}/><div><b>{row.creative.name}</b><small>{row.creative.brand} · {normalizeCreativeMedia(row.creative.platform)}</small><span><em className={statusTone(row)}>{row.score}점</em><>피로 {row.fatigueScore??'-'}</></span></div><ChevronRight size={16}/></button>):<p className="creative-analysis-empty">평가 가능한 소재 성과가 없습니다.</p>}</div></section></div>

    <div className="creative-analysis-two"><section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>광고비 vs 소재 성과</h3><p>고비용·저성과 소재와 저비용·고성과 후보를 분리합니다.</p></div></div><div className="creative-matrix"><span className="matrix-y">성과점수 ↑</span><span className="matrix-x">광고비 →</span><i className="matrix-v"/><i className="matrix-h"/>{scored.slice(0,18).map(row=>{const maxSpend=Math.max(...scored.map(r=>r.spend),1),x=10+row.spend/maxSpend*80,y=88-(row.score??0)*0.72;return <button key={row.creative.id} style={{left:`${x}%`,top:`${y}%`,background:MEDIA_COLORS[normalizeCreativeMedia(row.creative.platform)]||'#64748b'}} title={`${row.creative.name} · ${row.score}점`} onClick={()=>updateParam('creative',row.creative.id)}/>})}<b className="quad q1">확대 후보</b><b className="quad q2">핵심 소재</b><b className="quad q3">관찰</b><b className="quad q4">교체 우선</b></div></section><section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>소재 효율 순위</h3><p>동일 광고주·매체·목적 내 상대평가를 우선합니다.</p></div></div><div className="creative-ranking">{scored.slice(0,8).map((row,index)=><button key={row.creative.id} onClick={()=>updateParam('creative',row.creative.id)}><span>{index+1}</span><CreativePreview row={row}/><div><b>{row.creative.name}</b><small>{row.creative.brand} · {row.creative.type}</small></div><strong>{row.score}점</strong></button>)}</div></section></div>

    <div className="creative-analysis-two"><section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>소재별 성과 추이</h3><p>현재 연결된 기존 소재 보고서 추이를 TOP 소재 기준으로 봅니다.</p></div></div><div className="creative-trend-stack">{scored.filter(r=>r.performance?.trend?.length).slice(0,5).map(row=><div key={row.creative.id}><div><b>{row.creative.name}</b><small>{normalizeCreativeMedia(row.creative.platform)} · {row.lifecycle}</small></div><Sparkline values={row.performance!.trend}/><strong>{row.score}점</strong></div>)}{!scored.some(r=>r.performance?.trend?.length)&&<p className="creative-analysis-empty">기간별 소재 성과 데이터가 없습니다.</p>}</div></section><section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>소재 피로도</h3><p>초기 대비 최근 추이·집행기간·빈도와 소재 관리 상태를 봅니다.</p></div></div><div className="creative-fatigue-list">{[...rows].sort((a,b)=>(b.fatigueScore??-1)-(a.fatigueScore??-1)).slice(0,8).map(row=><button key={row.creative.id} onClick={()=>updateParam('creative',row.creative.id)}><div><b>{row.creative.name}</b><small>{row.lifecycle}</small></div><i><span className={fatigueTone(row)} style={{width:`${row.fatigueScore??0}%`}}/></i><strong>{row.fatigueScore??'-'}</strong></button>)}</div></section></div>

    <div className="creative-analysis-two"><PatternTable title="후킹 · CTA 성과" rows={patterns.patterns.filter(p=>p.kind==='후킹'||p.kind==='CTA')}/><PatternTable title="소재 유형 · 태그 성과" rows={patterns.patterns.filter(p=>p.kind==='소재 유형'||p.kind==='태그')}/></div>

    <section className="card creative-analysis-panel"><div className="creative-panel-head"><div><h3>소재 상세 성과</h3><p>검색·정렬을 이용해 비용·CTR·DB·피로도 기준으로 좁혀볼 수 있습니다.</p></div><div className="creative-table-tools"><div><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="소재명·광고주·태그 검색"/></div><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="score">성과점수</option><option value="spend">광고비</option><option value="ctr">CTR</option><option value="cpa">DB 비용</option><option value="db">실제 DB</option><option value="fatigue">피로도</option></select><button onClick={()=>setDir(dir==='desc'?'asc':'desc')}>{dir==='desc'?'내림차순':'오름차순'}</button></div></div><div className="table-scroll"><table className="creative-analysis-table"><thead><tr><th>소재</th><th>광고주</th><th>매체</th><th>캠페인</th><th>유형</th><th>광고비</th><th>CTR</th><th>실제 DB</th><th>유효DB율</th><th>DB 비용</th><th>KPI</th><th>피로도</th><th>점수</th><th></th></tr></thead><tbody>{table.map(row=><tr key={row.creative.id}><td><div className="creative-table-name"><CreativePreview row={row}/><div><b>{row.creative.name}</b><small>{row.hookTypes.join(' · ')} · {row.cta}</small></div></div></td><td>{row.creative.brand}</td><td><span className="creative-media-dot" style={{background:MEDIA_COLORS[normalizeCreativeMedia(row.creative.platform)]||'#64748b'}}/>{normalizeCreativeMedia(row.creative.platform)}</td><td>{row.campaignName}</td><td>{row.creative.type}</td><td>{money(row.spend)}</td><td>{row.impressions?pct(row.ctr,2):'-'}</td><td>{row.hasDb?row.db.toLocaleString():'-'}</td><td>{row.hasDb?pct(row.validDbRate):'-'}</td><td>{row.cpa?money(row.cpa):'-'}</td><td>{row.kpiAchievement===undefined?'-':`${row.kpiAchievement.toFixed(0)}%`}</td><td><span className={`creative-state ${fatigueTone(row)}`}>{row.fatigueScore??'평가 보류'}</span></td><td><span className={`creative-state ${statusTone(row)}`}>{row.score===undefined?'-':row.score}</span></td><td><button className="creative-text-link" onClick={()=>updateParam('creative',row.creative.id)}>상세 분석</button></td></tr>)}{!table.length&&<tr><td colSpan={14}><p className="creative-analysis-empty">조건에 맞는 소재가 없습니다.</p></td></tr>}</tbody></table></div></section>

    <div className="creative-analysis-three"><section className="card creative-analysis-panel"><h3>확대 후보</h3><div className="creative-action-list">{expanded.length?expanded.map(row=><button key={row.creative.id} onClick={()=>updateParam('creative',row.creative.id)}><TrendingUp className="good"/><div><b>{row.creative.name}</b><small>{row.score}점 · 피로 {row.fatigueScore??'-'}</small></div><ChevronRight size={15}/></button>):<p className="creative-analysis-empty">최소 표본을 충족한 확대 후보가 없습니다.</p>}</div></section><section className="card creative-analysis-panel"><h3>교체 후보</h3><div className="creative-action-list">{replace.length?replace.map(row=><button key={row.creative.id} onClick={()=>updateParam('creative',row.creative.id)}><TrendingDown className="bad"/><div><b>{row.creative.name}</b><small>{row.score}점 · {row.lifecycle}</small></div><ChevronRight size={15}/></button>):<p className="creative-analysis-empty">뚜렷한 교체 후보가 없습니다.</p>}</div></section><section className="card creative-analysis-panel"><h3>성과 급변</h3><div className="creative-action-list">{[...rising,...falling].slice(0,6).map(row=>{const up=rising.includes(row);return <button key={row.creative.id} onClick={()=>updateParam('creative',row.creative.id)}>{up?<ArrowUpRight className="good"/>:<ArrowDownRight className="bad"/>}<div><b>{row.creative.name}</b><small>{up?'최근 추이 상승':'최근 추이 하락'}</small></div><ChevronRight size={15}/></button>})}{!rising.length&&!falling.length&&<p className="creative-analysis-empty">비교 가능한 급변 소재가 없습니다.</p>}</div></section></div>

    <section className="card creative-analysis-panel creative-winning-pattern"><div className="creative-panel-head"><div><h3>성과 우수 패턴</h3><p>표본이 충분한 패턴만 제작 참고 신호로 사용합니다.</p></div><span>분석 표본 {usable.length}개</span></div>{patterns.winning.length?<div className="creative-winning-grid">{patterns.winning.slice(0,6).map(p=><article key={p.key}><Sparkles size={18}/><b>{p.label}</b><small>{p.kind} · {p.count}개</small><span>성과점수 평균 <strong>{p.avgScore.toFixed(0)}</strong></span><em className={confidenceTone[p.confidence]}>신뢰도 {p.confidence}</em></article>)}</div>:<div className="creative-analysis-empty">현재는 우수 패턴을 확정할 표본이 부족합니다. 소재 성과/API와 creativeId 단위 DB가 쌓이면 자동으로 활성화됩니다.</div>}</section>

    <section className="card creative-analysis-panel creative-production-panel"><div><Wand2 size={24}/><div><h3>다음 소재 제작 제안</h3><p>{patterns.winning[0]?`${patterns.winning[0].label} 패턴을 기준으로 한 요소만 바꾼 파생 소재를 제작해 원본과 비교하세요.`:'현재 우수 소재의 후킹·CTA·형식을 유지하고 한 요소씩 분리해 테스트하는 제작 흐름을 권장합니다.'}</p></div></div>{best[0]?<div className="content-header-actions"><button className="btn primary" onClick={()=>createBrief(best[0])}><CopyPlus size={16}/> 이 패턴으로 새 광고 만들기</button><Link className="btn secondary" to={`/content/templates?sourceCreative=${encodeURIComponent(best[0].creative.id)}`}><FileText size={16}/> 템플릿으로 저장</Link></div>:<Link className="btn secondary" to="/content/ad-creation">광고 제작 열기</Link>}</section>

    <div className="creative-data-note"><AlertTriangle size={16}/><span>Google Sheets에서 소재 단위 DB를 연결하려면 creativeId 또는 소재명 컬럼을 추가하세요. 식별값이 없으면 캠페인/매체 DB를 소재에 임의 분배하지 않습니다.</span></div>
  </div>;
}
