import { useEffect, useMemo, useState } from 'react';
import { Database, FileSpreadsheet, Link2, Plus, RefreshCw, Settings2, X } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { ADVERTISERS } from '../data/operationsMock';
import { AUTOMATION_EVENT, loadCollectionConfigs, removeAutomationJob, saveCollectionConfigs, upsertAutomationJob } from '../automation/automationStore';
import type { DataCollectionCadence, DataCollectionConfig, DataCollectionSource } from '../automation/automationTypes';
import { loadDbConnections, loadDbRows } from '../utils/dbDataStore';
import { syncAllDbConnections } from '../utils/googleSheetDbSync';
import { validateDbRows } from '../automation/dataCollection/validateData';
import { HOWTOM_DATA_FIELDS } from '../automation/dataCollection/normalizeData';

const sourceLabel:Record<DataCollectionSource,string>={google_sheets:'Google Sheet',csv:'CSV',meta:'메타 API',naver:'네이버 API',google:'구글 API',kakao:'카카오 API',karrot:'당근 API'};
const sourceOptions=Object.entries(sourceLabel) as [DataCollectionSource,string][];
function cadenceSchedule(c:DataCollectionConfig){if(c.cadence==='manual')return undefined;if(c.cadence==='daily')return {scheduleType:'daily' as const,time:c.time,timezone:'Asia/Seoul'};if(c.cadence==='hourly')return {scheduleType:'custom' as const,time:c.time,timezone:'Asia/Seoul'};return {scheduleType:'daily' as const,time:c.time,timezone:'Asia/Seoul'};}

export function DataAutoCollectionPage(){
  const [revision,setRevision]=useState(0); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<DataCollectionConfig|null>(null); const [syncing,setSyncing]=useState(false); const [notice,setNotice]=useState('');
  useEffect(()=>{const fn=()=>setRevision(x=>x+1);window.addEventListener(AUTOMATION_EVENT,fn);window.addEventListener('howtom-db-connections-updated',fn as EventListener);window.addEventListener('howtom-db-data-updated',fn as EventListener);return()=>{window.removeEventListener(AUTOMATION_EVENT,fn);window.removeEventListener('howtom-db-connections-updated',fn as EventListener);window.removeEventListener('howtom-db-data-updated',fn as EventListener)}},[]);
  const configs=useMemo(()=>loadCollectionConfigs(),[revision]); const connections=useMemo(()=>loadDbConnections(),[revision]); const dbRows=useMemo(()=>loadDbRows(),[revision]); const quality=useMemo(()=>validateDbRows(dbRows),[dbRows]);
  const googleConnected=connections.some(c=>c.enabled&&Boolean(c.endpointUrl));
  const sourceState=(source:DataCollectionSource)=>source==='google_sheets'?(googleConnected?'연결됨':'연결 필요'):source==='csv'?'수동':'미연동';
  const saveConfig=(config:DataCollectionConfig)=>{const next=configs.some(c=>c.configId===config.configId)?configs.map(c=>c.configId===config.configId?config:c):[config,...configs];saveCollectionConfigs(next);const schedule=cadenceSchedule(config);const jobId=`collection-${config.configId}`;if(schedule&&config.enabled){upsertAutomationJob({jobId,name:`${config.advertiserName} · ${sourceLabel[config.source]} 데이터 동기화`,jobType:'data_sync',advertiserId:config.advertiserId,advertiserName:config.advertiserName,targetType:'data-source',targetId:config.configId,targetName:sourceLabel[config.source],schedule,status:'active',implementationStatus:config.source==='google_sheets'?'available':'mock',source:'data-collection',createdAt:config.createdAt,updatedAt:config.updatedAt})}else removeAutomationJob(jobId);setRevision(x=>x+1)};
  const deleteConfig=(config:DataCollectionConfig)=>{if(!confirm('수집 설정을 삭제할까요?'))return;saveCollectionConfigs(configs.filter(c=>c.configId!==config.configId));removeAutomationJob(`collection-${config.configId}`);setRevision(x=>x+1)};
  const syncSheets=async()=>{if(!googleConnected){setNotice('설정 → DB·Google Sheets 연동에서 Apps Script 연결을 먼저 등록해 주세요.');return}setSyncing(true);const results=await syncAllDbConnections();const ok=results.filter(r=>r.ok).length;const rows=results.reduce((n,r)=>n+r.rows.length,0);setNotice(`Google Sheet 동기화 완료: ${ok}/${results.length}개 연결 성공 · ${rows.toLocaleString()}개 집계 행`);setSyncing(false);setRevision(x=>x+1)};
  return <div className="automation-engine-page">
    <PageHeader title="데이터 자동 수집" description="광고주별 데이터 소스, 수집 주기와 정합성 상태를 관리합니다. 실제 광고 API는 연결 전까지 미연동으로 명확히 표시합니다." action={<button className="btn primary" onClick={()=>{setEditing(null);setShowForm(true)}}><Plus size={15}/> 수집 설정</button>}/>
    <div className="automation-pre-revenue-note"><b>저비용 수집 원칙</b><span>초기에는 Google Sheet·CSV와 1일 1회 또는 수동 동기화를 우선합니다. 광고 API와 24시간 서버 수집은 실제 유료 고객이 사용하는 매체부터 순차 활성화합니다.</span></div>
    {notice&&<div className="auto-inline-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
    <section className="auto-source-grid">{sourceOptions.map(([key,label])=><div className={`auto-source-card ${sourceState(key)==='연결됨'?'connected':sourceState(key)==='미연동'?'unconnected':''}`} key={key}><div>{key==='google_sheets'?<Database size={19}/>:key==='csv'?<FileSpreadsheet size={19}/>:<Link2 size={19}/>}<b>{label}</b></div><strong>{sourceState(key)}</strong><small>{key==='google_sheets'?'Apps Script Web App / DB 집계':key==='csv'?'사용자가 파일 업로드':'향후 실제 광고 API Connector 연결'}</small></div>)}</section>
    <div className="auto-kpi-grid collection-kpis"><div className="auto-kpi-card"><span>수집 설정</span><strong>{configs.length}개</strong><small>광고주별 설정</small></div><div className="auto-kpi-card"><span>활성 설정</span><strong>{configs.filter(c=>c.enabled).length}개</strong><small>수동 포함</small></div><div className="auto-kpi-card"><span>Google Sheet 연결</span><strong>{connections.filter(c=>c.enabled&&c.endpointUrl).length}개</strong><small>실제 등록된 연결</small></div><div className="auto-kpi-card"><span>현재 DB 집계 행</span><strong>{dbRows.length.toLocaleString()}건</strong><small>브라우저 저장 데이터</small></div><div className="auto-kpi-card"><span>데이터 품질</span><strong>{quality.quality==null?'평가 보류':`${quality.quality}%`}</strong><small>{quality.issues.length?`확인 필요 ${quality.issues.length}건`:'검출 이슈 없음'}</small></div></div>

    <section className="card auto-panel"><div className="auto-panel-head"><div><h3>광고주별 수집 설정</h3><p>설정 저장과 다음 실행 계산은 프론트에서 동작하며, 외부 API 미연동 소스는 실행되지 않습니다.</p></div>{googleConnected&&<button className="btn secondary" onClick={syncSheets} disabled={syncing}><RefreshCw size={14}/>{syncing?'동기화 중':'Google Sheet 지금 동기화'}</button>}</div><div className="table-scroll"><table className="data-table auto-table"><thead><tr><th>광고주</th><th>수집 소스</th><th>데이터</th><th>주기</th><th>수집 범위</th><th>연결 상태</th><th>최근 수집</th><th>작업</th></tr></thead><tbody>{configs.length===0?<tr><td colSpan={8} className="auto-table-empty">아직 수집 설정이 없습니다. 처음에는 Google Sheet 또는 수동 수집부터 등록하는 것을 권장합니다.</td></tr>:configs.map(c=><tr key={c.configId}><td><b>{c.advertiserName}</b></td><td>{sourceLabel[c.source]}</td><td>{c.dataTypes.map(x=>x==='ad'?'광고':'DB').join(' + ')}</td><td>{c.cadence==='manual'?'수동':c.cadence==='daily'?`매일 ${c.time}`:c.cadence==='hourly'?`${c.intervalHours||1}시간마다`:`사용자 지정 ${c.time}`}</td><td>{c.collectionRange==='previous_day'?'전일':c.collectionRange==='recent_3_days'?'최근 3일':'최근 7일'}{c.recheckDays?` · ${c.recheckDays}일 재검증`:''}</td><td><span className={`auto-source-state ${sourceState(c.source)==='연결됨'?'connected':sourceState(c.source)==='미연동'?'unconnected':'manual'}`}>{sourceState(c.source)}</span></td><td>{c.source==='google_sheets'?connections.find(x=>x.enabled)?.lastSyncAt?.replace('T',' ').slice(0,16)||'-':c.lastRunAt?.replace('T',' ').slice(0,16)||'-'}</td><td><div className="row-actions"><button className="btn secondary mini" onClick={()=>{setEditing(c);setShowForm(true)}}><Settings2 size={13}/>설정</button><button className="btn secondary mini" onClick={()=>deleteConfig(c)}>삭제</button></div></td></tr>)}</tbody></table></div></section>

    <div className="auto-two-column"><section className="card auto-panel"><div className="auto-panel-head"><div><h3>데이터 정합성 검사</h3><p>현재 저장된 실제 DB 집계 행을 기본 규칙으로 점검합니다.</p></div></div>{dbRows.length===0?<div className="auto-empty">검사할 DB 데이터가 없습니다.</div>:<><div className="auto-quality-summary"><strong>{quality.quality}%</strong><span>총 {dbRows.length.toLocaleString()}행 · 확인 필요 {quality.issues.length}건</span></div><div className="auto-health-lines"><div><span>음수 값</span><b>{quality.issues.filter(x=>x.type==='negative').length}건</b></div><div><span>퍼널 역전</span><b>{quality.issues.filter(x=>x.type==='funnel').length}건</b></div><div><span>필수값 누락</span><b>{quality.issues.filter(x=>x.type==='required').length}건</b></div><div><span>중복</span><b>{quality.issues.filter(x=>x.type==='duplicate').length}건</b></div></div></>}</section><section className="card auto-panel"><div className="auto-panel-head"><div><h3>수집 파이프라인</h3><p>실제 API 연결 후에도 동일한 단계로 처리하도록 구조를 고정합니다.</p></div></div><div className="auto-pipeline">{['Source','Fetch','Normalize','Validate','Deduplicate','Store','Aggregate','Analysis'].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div><small className="footnote">HOWTOM 공통 필드: {HOWTOM_DATA_FIELDS.join(' · ')}</small></section></div>
    {showForm&&<CollectionModal initial={editing} onClose={()=>setShowForm(false)} onSave={(c)=>{saveConfig(c);setShowForm(false)}}/>}
  </div>;
}

function CollectionModal({initial,onClose,onSave}:{initial:DataCollectionConfig|null;onClose:()=>void;onSave:(c:DataCollectionConfig)=>void}){
  const [advertiserId,setAdvertiserId]=useState(initial?.advertiserId||ADVERTISERS[0]?.id||''); const [source,setSource]=useState<DataCollectionSource>(initial?.source||'google_sheets'); const [ad,setAd]=useState(initial?.dataTypes.includes('ad')??true); const [db,setDb]=useState(initial?.dataTypes.includes('db')??true); const [cadence,setCadence]=useState<DataCollectionCadence>(initial?.cadence||'manual'); const [time,setTime]=useState(initial?.time||'07:00'); const [intervalHours,setIntervalHours]=useState(initial?.intervalHours||3); const [range,setRange]=useState<DataCollectionConfig['collectionRange']>(initial?.collectionRange||'previous_day'); const [recheckDays,setRecheckDays]=useState(initial?.recheckDays??0); const [enabled,setEnabled]=useState(initial?.enabled??true); const advertiser=ADVERTISERS.find(a=>a.id===advertiserId); const save=()=>{if(!ad&&!db)return;const now=new Date().toISOString();onSave({configId:initial?.configId||`collection-${Date.now()}`,advertiserId,advertiserName:advertiser?.name||advertiserId,source,dataTypes:[...(ad?['ad' as const]:[]),...(db?['db' as const]:[])],cadence,time,intervalHours:cadence==='hourly'?intervalHours:undefined,collectionRange:range,recheckDays,enabled,createdAt:initial?.createdAt||now,updatedAt:now,lastRunAt:initial?.lastRunAt,lastRunStatus:initial?.lastRunStatus,lastRowCount:initial?.lastRowCount,lastMessage:initial?.lastMessage})};
  return <div className="modal-backdrop"><div className="modal-card auto-modal"><div className="modal-head"><div><h3>{initial?'수집 설정 수정':'새 수집 설정'}</h3><p>미연동 광고 API를 선택해도 설정만 저장되며 실제 수집된 것처럼 처리하지 않습니다.</p></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="auto-modal-grid"><label>광고주<select value={advertiserId} onChange={e=>setAdvertiserId(e.target.value)}>{ADVERTISERS.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>수집 방식<select value={source} onChange={e=>setSource(e.target.value as DataCollectionSource)}>{sourceOptions.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><div className="span-2"><span className="auto-field-title">데이터 유형</span><div className="auto-check-row"><label><input type="checkbox" checked={ad} onChange={e=>setAd(e.target.checked)}/> 광고 데이터</label><label><input type="checkbox" checked={db} onChange={e=>setDb(e.target.checked)}/> DB 데이터</label></div></div><label>수집 주기<select value={cadence} onChange={e=>setCadence(e.target.value as DataCollectionCadence)}><option value="manual">수동</option><option value="daily">매일</option><option value="hourly">시간 간격</option><option value="custom">사용자 지정</option></select></label>{cadence!=='manual'&&cadence!=='hourly'&&<label>실행 시간<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>}{cadence==='hourly'&&<label>실행 간격<select value={intervalHours} onChange={e=>setIntervalHours(Number(e.target.value))}><option value={1}>1시간마다</option><option value={3}>3시간마다</option><option value={6}>6시간마다</option><option value={12}>12시간마다</option></select></label>}<label>수집 기간<select value={range} onChange={e=>setRange(e.target.value as DataCollectionConfig['collectionRange'])}><option value="previous_day">전일 데이터</option><option value="recent_3_days">최근 3일</option><option value="recent_7_days">최근 7일</option></select></label><label>재수집·재검증<select value={recheckDays} onChange={e=>setRecheckDays(Number(e.target.value))}><option value={0}>사용 안 함</option><option value={1}>최근 1일</option><option value={3}>최근 3일</option><option value={7}>최근 7일</option></select></label><label className="span-2 auto-switch-label"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> 이 수집 설정 사용</label></div>{!['google_sheets','csv'].includes(source)&&<div className="auto-warning-box">{sourceLabel[source]}는 현재 실제 Connector가 미연동입니다. 설정은 저장할 수 있지만 실제 수집·실행은 하지 않습니다.</div>}<div className="modal-actions"><button className="btn secondary" onClick={onClose}>취소</button><button className="btn primary" onClick={save} disabled={!ad&&!db}>저장</button></div></div></div>;
}
