import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, CheckCircle2, ChevronRight, Eye, MousePointerClick, Sparkles, Target, WalletCards } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { loadAllGeneratedReports } from '../features/reports/reportCore';
import { ADVERTISERS, MOCK_CAMPAIGNS } from '../data/operationsMock';
import { derived, formatMetric, loadPerformanceDataset, metricValue, pctChange, sumRows, type PerformanceMetric, type PerformancePoint } from '../analytics/integratedPerformance';

const metricNames:Record<PerformanceMetric,string>={spend:'광고비',impressions:'노출',clicks:'클릭',leads:'DB',revenue:'매출',ctr:'CTR',cpa:'CPA',roas:'ROAS'};
const mediaColors:Record<string,string>={'메타':'#4776ff','네이버':'#03c75a','구글 검색':'#6b7280','유튜브':'#ef4444','당근':'#ff6f0f','카카오':'#f5c400','틱톡':'#111827'};
const goodWhenDown=new Set<PerformanceMetric>(['cpa']);
const goodWhenUp=new Set<PerformanceMetric>(['leads','revenue','ctr','roas']);
const periodLabels=['오늘','어제','최근 7일','최근 14일','최근 30일','이번 달','지난달'] as const;

function iso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(date:string,n:number){const d=new Date(`${date}T00:00:00`);d.setDate(d.getDate()+n);return iso(d)}
function rangeFor(period:string,latest:string){const d=new Date(`${latest}T00:00:00`); if(period==='오늘') return [latest,latest] as const; if(period==='어제'){const x=addDays(latest,-1);return [x,x] as const;} if(period.startsWith('최근 ')){const n=Number(period.match(/\d+/)?.[0]||30);return [addDays(latest,-n+1),latest] as const;} if(period==='이번 달') return [`${latest.slice(0,7)}-01`,latest] as const; const p=new Date(d.getFullYear(),d.getMonth()-1,1); const e=new Date(d.getFullYear(),d.getMonth(),0); return [iso(p),iso(e)] as const;}
function comparisonRange(start:string,end:string,mode:string){if(mode==='비교 안 함') return ['', ''] as const; const days=Math.max(1,Math.round((+new Date(end)-+new Date(start))/86400000)+1); if(mode==='직전 동일기간') return [addDays(start,-days),addDays(start,-1)] as const; const shift=(value:string,months=0,years=0)=>{const d=new Date(`${value}T00:00:00`);d.setFullYear(d.getFullYear()-years);d.setMonth(d.getMonth()-months);return iso(d)}; if(mode==='전월') return [shift(start,1),shift(end,1)] as const; return [shift(start,0,1),shift(end,0,1)] as const;}
function inRange(date:string,start:string,end:string){return (!start||date>=start)&&(!end||date<=end)}
function aggregateDaily(rows:PerformancePoint[]){const map=new Map<string,ReturnType<typeof derived>>(); const dates=[...new Set(rows.map(r=>r.date))].sort(); dates.forEach(date=>map.set(date,derived(sumRows(rows.filter(r=>r.date===date))))); return dates.map(date=>({date,...map.get(date)!}));}
function poly(values:number[]){const max=Math.max(...values,1),min=Math.min(...values,0),span=max-min||1;return values.map((v,i)=>`${8+i/Math.max(1,values.length-1)*92},${72-(v-min)/span*58}`).join(' ')}
function scoreChange(metric:PerformanceMetric,change:number){if(goodWhenDown.has(metric)) return -change; if(goodWhenUp.has(metric)) return change; return change;}
function trendClass(metric:PerformanceMetric,change:number){const score=scoreChange(metric,change); return score>0?'good':score<0?'bad':'neutral'}
function primaryMetric(type:string):PerformanceMetric{return type==='revenue'?'roas':type==='lead'?'cpa':'clicks'}

export function IntegratedPerformanceAnalysisPage(){
  const [version,setVersion]=useState(0); const [params,setParams]=useSearchParams();
  const data=useMemo(()=>loadPerformanceDataset(),[version]);
  const [period,setPeriod]=useState('최근 30일'); const [comparison,setComparison]=useState('직전 동일기간'); const [advertiser,setAdvertiser]=useState(params.get('advertiser')||''); const [media,setMedia]=useState(params.get('media')||''); const [campaign,setCampaign]=useState(''); const [trendMetric,setTrendMetric]=useState<PerformanceMetric>('leads'); const [contributionMetric,setContributionMetric]=useState<PerformanceMetric>('leads');
  const [start,end]=rangeFor(period,data.latestDate); const [prevStart,prevEnd]=comparisonRange(start,end,comparison);
  const nameToId=Object.fromEntries(ADVERTISERS.map(a=>[a.name,a.id]));
  const campaigns=MOCK_CAMPAIGNS.filter(c=>!advertiser||c.advertiserId===nameToId[advertiser]);
  const campaignMedia=campaign?({'meta':'메타','instagram':'메타','naver':'네이버','google':'구글 검색','youtube':'유튜브','karrot':'당근'} as Record<string,string>)[MOCK_CAMPAIGNS.find(c=>c.id===campaign)?.platform||'']:'';
  const effectiveMedia=campaignMedia||media;
  const source=effectiveMedia?data.media:data.totals;
  const filtered=(s:string,e:string)=>source.filter(r=>(!advertiser||r.advertiser===advertiser)&&(!effectiveMedia||r.media===effectiveMedia)&&inRange(r.date,s,e));
  const currentRows=filtered(start,end), prevRows=filtered(prevStart,prevEnd); const now=derived(sumRows(currentRows)), prev=derived(sumRows(prevRows));
  const kpis:(PerformanceMetric)[]=['spend','impressions','clicks','leads','revenue','ctr','cpa','roas'];
  const daily=aggregateDaily(currentRows), prevDaily=aggregateDaily(prevRows);
  const summaryParts=[] as string[]; const leadCh=pctChange(now.leads,prev.leads), spendCh=pctChange(now.spend,prev.spend), cpaCh=pctChange(now.cpa,prev.cpa), roasCh=pctChange(now.roas,prev.roas);
  if(now.leads||prev.leads) summaryParts.push(`DB는 ${Math.abs(leadCh).toFixed(1)}% ${leadCh>=0?'증가':'감소'}`); if(now.spend||prev.spend) summaryParts.push(`광고비는 ${Math.abs(spendCh).toFixed(1)}% ${spendCh>=0?'증가':'감소'}`); if(now.cpa||prev.cpa) summaryParts.push(`CPA는 ${Math.abs(cpaCh).toFixed(1)}% ${cpaCh<=0?'개선':'악화'}`); if(now.roas||prev.roas) summaryParts.push(`ROAS는 ${Math.abs(roasCh).toFixed(1)}% ${roasCh>=0?'개선':'하락'}`);
  const mediaRows=data.medias.map(name=>{const c=derived(sumRows(data.media.filter(r=>r.media===name&&(!advertiser||r.advertiser===advertiser)&&inRange(r.date,start,end)))); const p=derived(sumRows(data.media.filter(r=>r.media===name&&(!advertiser||r.advertiser===advertiser)&&inRange(r.date,prevStart,prevEnd)))); return {name,c,p,change:pctChange(metricValue(c,contributionMetric),metricValue(p,contributionMetric))}}).filter(x=>x.c.spend||x.c.clicks||x.c.leads||x.c.revenue);
  const contribution=[...mediaRows].sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,7);
  const advertiserRows=data.advertisers.map(name=>{const cRows=data.totals.filter(r=>r.advertiser===name&&inRange(r.date,start,end)); const pRows=data.totals.filter(r=>r.advertiser===name&&inRange(r.date,prevStart,prevEnd)); const c=derived(sumRows(cRows)),p=derived(sumRows(pRows)); const type=cRows[0]?.reportType||'click'; const pm=primaryMetric(type); return {name,type,c,p,pm,change:pctChange(metricValue(c,pm),metricValue(p,pm))}}).filter(x=>x.c.spend||x.c.clicks||x.c.leads||x.c.revenue);
  const anomalies=mediaRows.flatMap(row=>{const out:{title:string;copy:string;tone:string}[]=[];const spend=pctChange(row.c.spend,row.p.spend),leads=pctChange(row.c.leads,row.p.leads),cpa=pctChange(row.c.cpa,row.p.cpa),roas=pctChange(row.c.roas,row.p.roas),ctr=pctChange(row.c.ctr,row.p.ctr); if(spend>30&&leads<5)out.push({title:`${row.name} 예산 급증`,copy:`광고비 +${spend.toFixed(0)}%, DB ${leads.toFixed(0)}%`,tone:'warning'}); if(row.c.cpa&&cpa>20)out.push({title:`${row.name} CPA 급등`,copy:`CPA가 ${cpa.toFixed(0)}% 상승했습니다.`,tone:'danger'}); if(row.c.roas&&roas<-20)out.push({title:`${row.name} ROAS 하락`,copy:`ROAS가 ${Math.abs(roas).toFixed(0)}% 하락했습니다.`,tone:'danger'}); if(row.c.ctr&&ctr<-20)out.push({title:`${row.name} CTR 하락`,copy:`CTR이 ${Math.abs(ctr).toFixed(0)}% 하락했습니다.`,tone:'warning'}); return out;}).slice(0,5);
  const priorities=mediaRows.map(row=>{const cpa=pctChange(row.c.cpa,row.p.cpa),roas=pctChange(row.c.roas,row.p.roas),leads=pctChange(row.c.leads,row.p.leads),spend=pctChange(row.c.spend,row.p.spend); const risk=Math.min(100,Math.max(0,(cpa>0?cpa*.7:0)+(roas<0?-roas*.6:0)+(leads<0?-leads*.8:0)+(spend>15&&leads<0?20:0))); return {...row,risk};}).sort((a,b)=>b.risk-a.risk).slice(0,3);
  const rising=[...advertiserRows].sort((a,b)=>scoreChange(b.pm,b.change)-scoreChange(a.pm,a.change)).slice(0,5), falling=[...advertiserRows].sort((a,b)=>scoreChange(a.pm,a.change)-scoreChange(b.pm,b.change)).slice(0,5);
  const topMedia=[...mediaRows].sort((a,b)=>b.change-a.change)[0];
  const changeQuery=(next:{advertiser?:string;media?:string})=>{const p=new URLSearchParams(params); if(next.advertiser!==undefined){next.advertiser?p.set('advertiser',next.advertiser):p.delete('advertiser');setAdvertiser(next.advertiser)} if(next.media!==undefined){next.media?p.set('media',next.media):p.delete('media');setMedia(next.media)} setParams(p,{replace:true});};
  return <div className="integrated-analysis-page">
    <header className="iap-head"><div><span>인사이트</span><h1>통합 성과 분석</h1><p>전체 성과를 비교하고 원인과 개선 우선순위를 분석합니다.</p></div><div className="iap-data-badge">데이터 기준 <b>{data.latestDate||'-'}</b></div></header>
    <section className="iap-filter-card"><label>분석기간<select value={period} onChange={e=>setPeriod(e.target.value)}>{periodLabels.map(v=><option key={v}>{v}</option>)}</select></label><label>비교기간<select value={comparison} onChange={e=>setComparison(e.target.value)}><option>직전 동일기간</option><option>전월</option><option>전년 동기간</option><option>비교 안 함</option></select></label><label>광고주<select value={advertiser} onChange={e=>{setAdvertiser(e.target.value);setCampaign('')}}><option value="">전체 광고주</option>{data.advertisers.map(v=><option key={v}>{v}</option>)}</select></label><label>매체<select value={media} onChange={e=>{setMedia(e.target.value);setCampaign('')}}><option value="">전체 매체</option>{data.medias.map(v=><option key={v}>{v}</option>)}</select></label><label>캠페인<select value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">전체 캠페인</option>{campaigns.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>대표 KPI<select defaultValue="대표 KPI"><option>대표 KPI</option><option>DB</option><option>ROAS</option><option>CPA</option><option>클릭</option></select></label></section>
    <section className="iap-kpi-grid">{kpis.map(metric=>{const n=metricValue(now,metric),p=metricValue(prev,metric),ch=pctChange(n,p),cls=trendClass(metric,ch); const Icon=metric==='spend'?WalletCards:metric==='impressions'?Eye:metric==='clicks'?MousePointerClick:metric==='leads'?Target:BarChart3; return <article className="iap-kpi" key={metric}><div className="iap-kpi-top"><span>{metricNames[metric]}</span><Icon size={18}/></div><strong>{formatMetric(metric,n)}</strong><em className={cls}>{ch>=0?<ArrowUpRight/>:<ArrowDownRight/>}{Math.abs(ch).toFixed(1)}% <small>vs 비교기간</small></em></article>})}</section>
    <section className="iap-summary"><Sparkles size={23}/><div><strong>{leadCh>=0&&cpaCh<=0?'전반적인 광고 효율이 개선되고 있습니다.':'성과 변화가 감지되었습니다.'}</strong><p>{summaryParts.join(' · ')||'비교 가능한 데이터가 충분하지 않습니다.'}</p></div></section>
    <section className="iap-main-grid"><article className="iap-panel iap-trend"><div className="iap-panel-head"><div><h2>핵심 성과 추이</h2><p>{start} ~ {end}</p></div><div className="iap-tabs">{(['spend','leads','revenue','cpa','roas','ctr'] as PerformanceMetric[]).map(m=><button className={trendMetric===m?'active':''} onClick={()=>setTrendMetric(m)} key={m}>{metricNames[m]}</button>)}</div></div><svg viewBox="0 0 100 82" preserveAspectRatio="none" className="iap-line-chart"><line x1="8" y1="72" x2="100" y2="72"/><polyline className="previous" points={poly(prevDaily.map(d=>metricValue(d,trendMetric)))}/><polyline className="current" points={poly(daily.map(d=>metricValue(d,trendMetric)))}/></svg><div className="iap-chart-legend"><span><i className="solid"/>현재 기간</span><span><i className="dash"/>비교 기간</span><b>{formatMetric(trendMetric,metricValue(now,trendMetric))}</b></div></article>
    <article className="iap-panel"><div className="iap-panel-head"><div><h2>개선 우선순위</h2><p>위험 점수 기준</p></div></div><div className="iap-priority-list">{priorities.map((p,i)=><button key={p.name} onClick={()=>changeQuery({media:p.name})}><span>{i+1}순위</span><div><b>{p.name} 점검</b><small>위험도 {p.risk.toFixed(0)}점 · CPA/ROAS/전환 변화를 종합했습니다.</small></div><ChevronRight/></button>)}</div></article></section>
    <section className="iap-mid-grid"><article className="iap-panel"><div className="iap-panel-head"><div><h2>성과 변화 원인</h2><p>매체별 기여도</p></div></div><div className="iap-tabs compact">{(['leads','revenue','spend','roas'] as PerformanceMetric[]).map(m=><button className={contributionMetric===m?'active':''} onClick={()=>setContributionMetric(m)} key={m}>{m==='leads'?'전환 기여도':`${metricNames[m]} 변화`}</button>)}</div><div className="iap-contribution">{contribution.map(row=><div key={row.name}><span>{row.name}</span><i><b style={{width:`${Math.min(100,Math.max(8,Math.abs(row.change)))}%`,background:row.change>=0?(mediaColors[row.name]||'#4776ff'):'#ef4444'}}/></i><strong className={row.change>=0?'good':'bad'}>{row.change>=0?'+':''}{row.change.toFixed(1)}%</strong></div>)}</div></article>
    <article className="iap-panel"><div className="iap-panel-head"><div><h2>이상 징후</h2><p>설정된 임계값을 기준으로 자동 탐지</p></div></div><div className="iap-anomaly-list">{anomalies.length?anomalies.map((a,i)=><div className={a.tone} key={i}><AlertTriangle/><div><b>{a.title}</b><small>{a.copy}</small></div></div>):<div className="ok"><CheckCircle2/><div><b>중대한 이상 징후 없음</b><small>현재 선택 범위에서 즉시 대응이 필요한 변화가 없습니다.</small></div></div>}</div></article></section>
    <section className="iap-panel"><div className="iap-panel-head"><div><h2>매체별 성과</h2><p>행의 상세 분석 버튼은 현재 화면 필터로 드릴다운합니다.</p></div></div><div className="table-scroll"><table><thead><tr><th>매체</th><th>광고비</th><th>클릭</th><th>DB</th><th>CPA</th><th>매출</th><th>ROAS</th><th>변화</th><th>상세</th></tr></thead><tbody>{mediaRows.map(row=><tr key={row.name}><td><span className="iap-media-dot" style={{background:mediaColors[row.name]||'#94a3b8'}}/>{row.name}</td><td>{formatMetric('spend',row.c.spend)}</td><td>{formatMetric('clicks',row.c.clicks)}</td><td>{formatMetric('leads',row.c.leads)}</td><td>{formatMetric('cpa',row.c.cpa)}</td><td>{formatMetric('revenue',row.c.revenue)}</td><td>{formatMetric('roas',row.c.roas)}</td><td className={row.change>=0?'good':'bad'}>{row.change>=0?'+':''}{row.change.toFixed(1)}%</td><td><button className="iap-link-button" onClick={()=>changeQuery({media:row.name})}>상세 분석</button></td></tr>)}</tbody></table></div></section>
    <section className="iap-panel"><div className="iap-panel-head"><div><h2>광고주별 성과</h2><p>광고주 유형에 따라 대표 KPI를 다르게 평가합니다.</p></div></div><div className="table-scroll"><table><thead><tr><th>광고주</th><th>유형</th><th>광고비</th><th>클릭</th><th>DB</th><th>매출</th><th>대표 KPI</th><th>변화</th><th>상세</th></tr></thead><tbody>{advertiserRows.map(row=><tr key={row.name}><td>{row.name}</td><td>{row.type==='lead'?'DB형':row.type==='revenue'?'매출형':'클릭형'}</td><td>{formatMetric('spend',row.c.spend)}</td><td>{formatMetric('clicks',row.c.clicks)}</td><td>{formatMetric('leads',row.c.leads)}</td><td>{formatMetric('revenue',row.c.revenue)}</td><td>{metricNames[row.pm]} {formatMetric(row.pm,metricValue(row.c,row.pm))}</td><td className={scoreChange(row.pm,row.change)>=0?'good':'bad'}>{row.change>=0?'+':''}{row.change.toFixed(1)}%</td><td><button className="iap-link-button" onClick={()=>changeQuery({advertiser:row.name})}>상세 분석</button></td></tr>)}</tbody></table></div></section>
    <section className="iap-bottom-grid"><article className="iap-panel"><h2>성과 급상승 TOP 5</h2><ol className="iap-rank-list">{rising.map((r,i)=><li key={r.name}><span>{i+1}</span><div><b>{r.name}</b><small>{metricNames[r.pm]} 기준</small></div><strong className="good">+{Math.max(0,r.change).toFixed(1)}%</strong></li>)}</ol></article><article className="iap-panel"><h2>성과 급하락 TOP 5</h2><ol className="iap-rank-list">{falling.map((r,i)=><li key={r.name}><span>{i+1}</span><div><b>{r.name}</b><small>{metricNames[r.pm]} 기준</small></div><strong className="bad">{Math.min(0,r.change).toFixed(1)}%</strong></li>)}</ol></article><article className="iap-panel iap-insights"><h2>주요 인사이트</h2><ul><li><b>성과</b>{leadCh>=0?`DB가 비교기간보다 ${leadCh.toFixed(1)}% 증가했습니다.`:`DB가 ${Math.abs(leadCh).toFixed(1)}% 감소했습니다.`}</li><li><b>주요 원인</b>{topMedia?`${topMedia.name}의 변화폭이 가장 크게 나타났습니다.`:'매체별 비교 데이터가 부족합니다.'}</li><li><b>주의</b>{anomalies[0]?.copy||'즉시 대응이 필요한 주요 이상 징후는 없습니다.'}</li><li><b>추천</b>{priorities[0]?`${priorities[0].name}의 예산·소재·전환 흐름을 우선 점검하세요.`:'현재 성과 흐름을 유지하세요.'}</li></ul><Link to="/monthly-reports">월간 보고서에서 확인 <ChevronRight size={16}/></Link></article></section>
  </div>
}
